### ISSUE TITLE
f-spz-cttnord: 404

### ISSUE THREAD

**Issue by irees** [transitland/transitland#101]
https://transit.land/dispatcher/feeds/f-spz-cttnord

**Comment by stevevance** [comment]
This is for Compagnia Toscana Trasporti - Nord https://transit.land/feed-registry/operators/o-spz-cttnord. 

This is an unstable URL, because the data portal changes it, I believe, each time the feed is updated. 

It's currently at: http://dati.toscana.it/dataset/8bb8f8fe-fe7d-41d0-90dc-49f2456180d1/resource/928f7151-acae-4f1f-8cde-b589a6c98ba2/download/ctt.gtfs
