### ISSUE TITLE
Feed for Consorsio Atlantico Sul and Consorsio Sudoeste, São Paulo

### ISSUE THREAD

**Issue by rmglennon** [transitland/transitland#115]
We received an email with a sample GTFS zip file attached. The feed is handmade and hosted on http://www.adoniascorreaoficial.pe.hu/gtfs/

I attempted to add it to the feed registry, but was unable to proceed using the files at that URL. So, there is not currently a changeset for this feed.

Information from the agency.txt: 
agency_id,agency_name,agency_url,agency_timezone
CAS,Consorsio Atlantico Sul,http://viacaopraiasol.com.br,America/Sao_Paulo
CS,Consorsio Sudoeste,http://gruposantazita.com.br,America/Sao_Paulo,

See support tickets # 837 and 885 for details.

**Comment by drewda** [comment]
@rmglennon and I will have a look at the Feed Registry error together. At a minimum, we can paste the generated changeset JSON payload here for future follow-up.

**Comment by acorrea1** [comment]
In fact desire to accomplish the first insert, because this operator does not exist in the system you.

*** Translated by [Google platform](https://translate.google.com.br/#pt/en/Na%20verdade%20desejo%20realizar%20a%20primeira%20inser%C3%A7%C3%A3o%2C%20pois%2C%20este%20operador%20n%C3%A3o%20existe%20no%20sistema%20de%20voc%C3%AAs.%0A%0AAtt%3B%0AAdonias%20Corr%C3%AAa)

**Comment by drewda** [comment]
Closing this since we, unfortunately, didn't finish debugging at the time, and it doesn't look like the creator of the feeds has posted any newer versions over the last ~6 months.
