### ISSUE TITLE
remove all entities except operator for Mountain Line transit

### ISSUE THREAD

**Issue by rmglennon** [transitland/transitland#225]
Determine the workflow for when a feed that is currently in the feed registry has expired and will not be updated or can no longer be accessed. 

Can Transitland keep it around and mark it as historical so people will know the data is out-of-date, or does it remove the feed entirely?

For example, [Mountain Line transit in Flagstaff, AZ](https://transit.land/feed-registry/operators/o-9w28-mountainline) has moved to a host that requires a token to download the GTFS.

(details in support ticket 1760)

**Comment by drewda** [comment]
Since we'll no longer have updated to this feed, let's remove the feed record along with all of the entities we've imported from it (stops, routes, schedule data). We can hold on to the operator record (o-9w28-mountainline) so that the agency is still listed, with its country/state/metro and service area geometry.

**Comment by drewda** [comment]
Done.

---

```ruby
o = Operator.find_by_onestop_id!('o-9w28-mountainline')
o.routes.each(&:destroy_making_history)
o.stops.each(&:destroy_making_history)
o.schedule_stop_pairs.delete_all
```
