### ISSUE TITLE
SF Bay Ferry query returns vehicle type of tram, rather than ferry

### ISSUE THREAD

**Issue by rmglennon** [transitland/transitland#240]
I did a little digging, but could use some help figuring out what's happening here. If you do a query for anything that includes results from o-9q9p-sanfranciscobayferry, it indicates that the vehicle_type is tram, rather than ferry.

Feed registry query: https://transit.land/feed-registry/operators/o-9q9p-sanfranciscobayferry

Example: https://transit.land/api/v1/routes?&vehicle_type=tram&bbox=-122.79144287109375,37.49883141715704,-120.81802368164061,38.28670289852796 
or https://transit.land/api/v1/routes?operated_by=o-9q9p-sanfranciscobayferry

You get results from SF Muni for the bbox area query, which is as expected, but also, all these ferries from this operator.

```
"onestop_id": "r-9q8z-vallejo~sf",
"name": "Vallejo-SF",
"vehicle_type": "tram",
"color": null,
"tags": {},
```

In the routes.txt, route_type=4 is the code for ferry (unless it's missing a required field and being misread or something?).
route_id,agency_id,route_short_name,route_long_name,route_type,route_color,route_text_color
Ala-Oak-SF,SB,Ala-Oak-SF,,4,,
Harbor Bay-SF,SB,Harbor Bay-SF,,4,,
South SF-East Bay,SB,South SF-East Bay,,4,,
South SF-SF,SB,South SF-SF,,4,,
Vallejo-SF,SB,Vallejo-SF,,4,,

**Comment by drewda** [comment]
@irees please investigate when you're back.

If there's an issue with the current version of the feed, I can follow up with our contact at 511.org.

**Comment by irees** [comment]
@rmglennon 

The (currently imported version)[https://transit.land/dispatcher/feed-versions/29429895dabfa3c42a41c089d0c4d2cdd57c85cd] uses `route_type: 0`, for tram. It was imported about 2 weeks ago. More (recent versions)[https://transit.land/dispatcher/feed-versions/2fac3f7f2a0acb751aed8c1d47e9f661fef72d8e] use `route_type: 4` for ferry, which is correct. They weren't automatically imported because the service start date began earlier than the currently imported version. I will trigger a manual import; it will be updated immediately in the API, and will roll out in the next tile build.

**Comment by irees** [comment]
Done - https://transit.land/dispatcher/changesets/5983

**Comment by irees** [comment]
Enqueued for import. Closing.
