### ISSUE TITLE
San Joaquin Regional Transit District (RTD) o-9qc-sanjoaquinregionaltransitdistrictrtd in datastore missing routes in operated_by / is not the latest feed?

### ISSUE THREAD

**Issue by joordan** [transitland/transitland#316]
Hello, I've been experimenting with the transitland api and so far it's been great but I noticed when using 

`api/v1/routes?operated_by=o-9qc-sanjoaquinregionaltransitdistrictrtd` 

to get routes for San Joaquin RTD, it seems to be missing some routes.

I can verify that the 'Fetched from URL' is correct and has the latest routes. 

You can also see the list of routes in the [transitfeeds website](https://transitfeeds.com/p/san-joaquin-rtd/347/latest/routes)

For example, some missing routes are route 150, 47, 49.

But the strange thing is.. I can do 

`api/v1/route_stop_patterns?traversed_by=r-9q9zb-47` 
`api/v1/route_stop_patterns?traversed_by=r-9q9zb-49`

and see it actually exists?

The stop patterns found at those endpoints match the stops in the GTFS.

For some reason it seems like `routes?operated_by=` isn't returning all the routes. If this is due to a specific problem in the GTFS, let me know. I manage San Joaquin RTD's GTFS.

**Comment by joordan** [comment]
Sorry I mean to label this as 'data questions/debugging'. How can I do that?

**Comment by drewda** [comment]
@joordan thanks for your question (and for managing this feed).

My first guess is the issue is pagination. When you query http://transit.land/api/v1/routes?operated_by=o-9qc-sanjoaquinregionaltransitdistrictrtd you will only receive the first 50 relevant routes, by default.

If you advance to the next page of results (https://api.transit.land/api/v1/routes?offset=50&operated_by=o-9qc-sanjoaquinregionaltransitdistrictrtd&per_page=50&sort_key=id&sort_order=asc), you'll see routes 150, 47, and 49.

Alternatively, you can query for unlimited results by running: http://transit.land/api/v1/routes?operated_by=o-9qc-sanjoaquinregionaltransitdistrictrtd&per_page=false (Note that this can sometimes lead to giant queries that will be stopped if they take longer than 2 minutes.)

Hope this helps -- if not feel free to reopen and follow up with more questions.

**Comment by joordan** [comment]
Thanks Drew, you've been helpful. Transitland is a really great api.
