### ISSUE TITLE
User tried to upload a feed and saw an error

### ISSUE THREAD

**Issue by migurski** [transitland/transitland#39]
https://www.phoenix.gov/publictransitsite/Documents/phx_transit_gis.zip 

See also https://mapzen.slack.com/archives/support/p1457092689000002

**Comment by drewda** [comment]
This is a set of shapefiles, rather than a GTFS feed. Transitland can only accept a GTFS feed (or a transit-data format that can be converted into a GTFS feed). Shapefiles do not have the schedule data that's necessary.

@migurski please suggest to the user who sent in the support request that they try the Transitland Feed Registry "add a feed" flow using the following URL: https://www.phoenix.gov/publictransitsite/Documents/google_transit.zip (which is listed at the bottom of https://www.phoenix.gov/publictransit/developers-portal ) I've already confirmed that the URL for that GTFS feed will work--but we can let that user actually submit the feed him/herself.
