### ISSUE TITLE
cross-reference against US DOT National Transit Map (NTM) & National Transit Database (NTD)

### ISSUE THREAD

**Issue by drewda** [transitland/transitland#5]
The US Department of Transportation tracks American transit agencies in two datasets: the National Transit Database (NTD) and the National Transit Map (NTM). Let's cross-reference Transitland operator and feed records with the NTD and NTM, so it's possible for users to use all of these data sources together.

Tasks:
- [x] Review the feeds currently represented in the NTM and add any that are missing in the Feed Registry.
- [x] Add US NTD IDs to the `identifiers` array on the respective Transitland operator records.
- ~~[ ] For all the feeds and operators that are represented in the NTM, add a tag like `us_national_transit_map: true` so it's possible to filter for that subset through the Datastore API.~~ no longer relevant now that US NTD IDs are in tags

Relevant files:
- A spreadsheet of all the feeds currently represented in the National Transit Map, along with their source URLs and US NTD IDs: 
  [FeedsInfo.xlsx](https://github.com/transitland/transitland/files/527831/FeedsInfo.xlsx)
- A list of all transit agencies in the US NTD and their US NTD IDs (many more than represented in the NTM): 
  [US NTD August 2016 Raw Database MASTER tab.csv.txt](https://github.com/transitland/transitland/files/527705/US.NTD.August.2016.Raw.Database.MASTER.tab.csv.txt). (I extracted this CSV from one of the tabs a large Excel spreadsheet at https://www.transit.dot.gov/ntd/data-product/monthly-module-raw-data-release)

**Comment by stevevance** [comment]
*open questions...*
How many feeds are there in the U.S. National Transit Map
How many feeds are missing from the that map?

The Feed Registry currently has 398 "operators" (I don't know how many feeds that correlates to).

**Comment by drewda** [comment]
@stevevance I've updated the issue description with more relevant information, including a spreadsheet that lists out source URLs for the feeds represented in the NTM.

**Comment by irees** [comment]
Example to add identifier:

```
{
	"changes": [{
		"action": "createUpdate",
		"stop": {
			"onestopId": "s-9q8yt4b-1AvHoS",
			"identifiedBy": ["gtfs://sfmta/53532"]
		}
	}]
}
```

**Comment by stevevance** [comment]
Given a feed URL, what's the most efficient way to check if that URL is in our datastore?

I've run a few through the "add new feed" form in the Feed Registry, but this is taking too long for feeds that have more than a handful of routes and stops.

**Comment by stevevance** [comment]
Is this how I would do it for an operator?
Will setting the array on the `identifiedBy` property overwrite or append any existing array items?

````
{
    "changes": [{
        "action": "createUpdate",
        "operator": {
            "onestopId": "o-9rb-lanetransitdistrict",
            "identifiedBy": ["usntd://sfmta/00007"]
        }
    }]
}
````

**Comment by drewda** [comment]
@stevevance if you can prepare a CSV listing operator Onestop ID and matching US NTD ID, then it will be really straightforward to turn that into changeset JSON payloads. Instead of writing a script, you could even just use a text editor that allows multiple cursors, like Sublime, Atom, or Visual Studio Code--you just select the entire CSV, put a cursor at the end of every line, and then write out the surrounding JSON syntax.

**Comment by stevevance** [comment]
I tried out the multiple cursors thing. It took a few minutes and a few tries to get it to work properly (it doesn't like tab-separated values if there's a different number of tabs between the fields).

I created a [test changeset](https://transit.land/dispatcher/changesets/3135) that contains 10 Onestop IDs. Can you look at them @drewda @irees? It should exactly like the syntax in Drew's comment 3 comments up.

**Comment by drewda** [comment]
@stevevance 👍

**Comment by drewda** [comment]
To query for operators that now have attached US NTD IDs: http://transit.land/api/v1/operators?identifier_starts_with=usntd&total=true

**Comment by stevevance** [comment]
Through my work cross-referencing the NTD IDs with existing operators in the Transitland Feed Registry, I found 178 NTD IDs for 183 Transitland operators. All of those have been applied. The Feed Registry now contains 185 operators with `usntd://` identifiers. 

Many operators had an incorrect NTD ID, and the actual ID is marked in a new column called `Actual NTDID` [in my own spreadsheet](https://docs.google.com/spreadsheets/d/1H9BASaftH6D6hjtP0t6cbj5VfzulVWeXm1inxy26b4Q/edit?usp=sharing). 

68 operators in the NTD's `FeedsInfo.xlsx` spreadsheet could not be applied to the Feed Registry because they hosted feeds on FTP (#34), were duplicates, or had no feed. These are marked with a `9` in the `NTDID verified` column in my spreadsheet. 

I couldn't verify the NTD ID for 13 operators in the NTD spreadsheet. Eleven of these feeds shared the Massachusetts Bay Transportation Authority's (MBTA) NTD ID, `10003`, but I don't know if that's the right practice. It could be that these smaller operators do not report to the U.S. DOT. The other 2 operators had NTD IDs that couldn't be verified. These are marked with a `2` in the `NTDID verified` column in my spreadsheet.

**Comment by drewda** [comment]
We've now moved all US NTD IDs into tags (see https://github.com/transitland/transitland/issues/217).

To see operators that have a US NTD ID attached, use this query: http://transit.land/api/v1/operators?tag_key=us_ntd_id
