### ISSUE TITLE
Change a onestopId for Trenitalia-Piemonte

### ISSUE THREAD

**Issue by stevevance** [transitland/transitland#66]
For [changeset 1300](https://transit.land/dispatcher/changesets/1300), the operator was submitted as "Trenitalia", but I changed the name to "Trenitalia-Piemonte" because Trenitalia is a national intercity train brand and this feed is for the Piemonte (Piedmont in English) state. 

The current onestopId is `o-u0j-trenitalia` but I'd like to change it to `o-u0j-trenitalia-piemonte` so that it doesn't seem superior to other states' Trenitalia networks.

**Comment by drewda** [comment]
@stevevance since the changeset hasn't been applied yet (and a database record at http://transit.land/api/v1/operators/o-u0j-trenitalia hasn't been created yet), you should be able to just edit the JSON payload and change the two times the operator Onestop ID is used in the changeset, before you apply it.

**Comment by stevevance** [comment]
@drewda I changed the onestopId but it wouldn't update. This is the error I get (I can't copy/paste it because it disappears as soon as I try to click on it):

<img width="1417" alt="screenshot 2016-07-27 08 52 43" src="https://cloud.githubusercontent.com/assets/1330459/17177561/9fa9ec48-53d7-11e6-9149-d3876b73c3f9.png">

**Comment by stevevance** [comment]
The problem is that I was trying to use hyphens, which are protected characters. If I want to extend/append a `onestopId` I must use a tilde `~`.
